### ISSUE TITLE
[Bug]: Plugin causes Jellyfin to crash when scanning series

### ISSUE THREAD

**Issue by wolffshots** [tubearchivist/tubearchivist-jf-plugin#25] opened 2024-10-22 13:08 UTC
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

When scanning libraries the `OnWatchedStatusChange` is fired when scanning my normal Series library which causes this line to crash the Jellyfin server:
```cs
itemYTId = Utils.GetVideoNameFromPath(eventArgs.Item.Path);
```
I have specifically disabled the TubeArchvist plugin for the Series library but the issue persists unless I disable the plugin.

## Steps To Reproduce

- Install TubeArchvist JF plugin version 1.3.2 and start a full library scan. 
- When it gets to scanning Series it restarts the Jellyfin server because of the crash.
- Server starts back up, restarts scan and crashes again and this repeats every few minutes indefinitely

## Expected behavior

- Install TubeArchvist JF plugin version 1.3.2 and start a full library scan and have the scan complete successfully for all libraries

### Relevant Jellyfin log output

```shell
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Jellyfin.Plugin.TubeArchivistMetadata.Utilities.Utils.DetectDirectorySeparator(String path)
   at Jellyfin.Plugin.TubeArchivistMetadata.Utilities.Utils.GetVideoNameFromPath(String path)
   at Jellyfin.Plugin.TubeArchivistMetadata.Plugin.OnWatchedStatusChange(Object sender, UserDataSaveEventArgs eventArgs)
```

### Anything else?

I've got a fork with a workaround [here](https://github.com/wolffshots/tubearchivist-jf-plugin/) that I have been testing that I will open a PR for soon once I have made a branch for the specific fix.

**Comment by wolffshots** [comment] 2024-10-23 16:22
Yeah I'm 100% sure I don't have it enabled on my normal Series collection and it's not an option on any other collections. Any other ideas what could be causing this?

It seems to happen every time I run a scan on my Series collection but the other seem to work fine (including the TA collection)

**Comment by DreizackLP** [comment] 2024-11-01 01:02
I have the same Problem

**Comment by DarkFighterLuke** [comment] 2024-11-04 21:31
@wolffshots PR has been merged. I am closing this issue as I assume the fix will work (I was not able to reproduce the original error).

**Closed by DarkFighterLuke** 2024-11-04 21:31 UTC
